// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wallet-layouts/ActionGrid.tsx": () => import("../components/mockups/wallet-layouts/ActionGrid.tsx"),
  "./components/mockups/wallet-layouts/BankCard.tsx": () => import("../components/mockups/wallet-layouts/BankCard.tsx"),
  "./components/mockups/wallet-layouts/StatsBar.tsx": () => import("../components/mockups/wallet-layouts/StatsBar.tsx")
};
